name: CI/CD for Nginx on Lightsail

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Nginx Docker image
        run: |
          docker build -t nginx-app .

      - name: Save Docker image as tarball
        run: |
          docker save nginx-app > nginx-app.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-docker-image
          path: nginx-app.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: nginx-docker-image

      - name: Load Docker image
        run: |
          docker load < nginx-app.tar

      - name: Run container and test
        run: |
          docker run -d --name test-nginx -p 8080:80 nginx-app
          sleep 5
          curl -f http://localhost:8080 || (echo "Test failed" && exit 1)

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: nginx-docker-image

      - name: Copy Docker image to Lightsail
        run: |
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no nginx-app.tar ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/home/${{ secrets.LIGHTSAIL_USER }}

      - name: Deploy to Lightsail
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            docker load < nginx-app.tar
            docker stop nginx || true
            docker rm nginx || true
            docker run -d --name nginx -p 80:80 nginx-app
          EOF
